name: CI

#on:

#   pull_request:
#     branches:
#       - main

env:
  AWS_REGION: ap-southeast-2

jobs:

  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest

    outputs:
      terraform: ${{ steps.filter.outputs.terraform }}
      code: ${{ steps.filter.outputs.code }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check changed paths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            terraform:
              - 'terraform/**'
            code:
              - 'code/*.py'
              - 'requirements.txt'

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.code == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: python -m unittest discover -s tests


  SAST:
    name: 🔗 Snyk SAST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Snyk Terraform Scan
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: terraform
          args: --severity-threshold=high

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

  call-terraform-plan-dev:
    name: Call Terraform Plan
    needs: [detect-changes]
    if: |
      needs.detect-changes.outputs.terraform == 'true'
    uses: ./.github/workflows/tfplan.yml
    with:
      environment: dev
    secrets: inherit
